### PR TITLE
Add ability to play remote (HTTP) files and to seek by -/+ 30 seconds.

### PR DESCRIPTION
**Pull request by ThomasLebrun**

### CODE REVIEW

**Comment by alessandro-pezzato** [comment]
Thank you for the pull request. Please, try to change the less code possible:

 - remove the commented resolvePath
 - use return instead of else

```
if(video.indexOf('http://') > -1) {
  ret.push(video);
  currentVideos.push(video);
}
else
{
  var realPath = path.resolve(videoDir, video + videoSuffix);
```

becomes:

```
if(video.indexOf('http://') === 0) {
  ret.push(video);
  currentVideos.push(video);
  return;
}
var realPath = path.resolve(videoDir, video + videoSuffix);
```

**Comment by ThomasLebrun** [comment]
Hi,

I'm not sure to understand why I should use "return":
Using a return will exit the foreach so it will work for only 1 video (but we may pass an array of remote videos) so I would not use this.


Thanks,

---
Thomas LEBRUN
________________________________
De : Alessandro Pezzato<mailto:notifications@github.com>
Envoyé : ‎24/‎02/‎2015 01:24
À : alessandro-pezzato/omxdirector<mailto:omxdirector@noreply.github.com>
Cc : Thomas LEBRUN<mailto:lebrun_thomas@hotmail.com>
Objet : Re: [omxdirector] Add ability to play remote (HTTP) files and to seek by -/+ 30 seconds. (#8)

Thank you for the pull request. Please, try to change the less code possible:

 - remove the commented resolvePath
 - use return instead of else

```
if(video.indexOf('http://') > -1) {
  ret.push(video);
  currentVideos.push(video);
}
else
{
  var realPath = path.resolve(videoDir, video + videoSuffix);
```

becomes:

```
if(video.indexOf('http://') === 0) {
  ret.push(video);
  currentVideos.push(video);
  return;
}
var realPath = path.resolve(videoDir, video + videoSuffix);
```

---

**Comment by alessandro-pezzato** [comment]
return doesnt break the loop here, it exits the forEach closure. this is
not a for loop.

Il giorno Mar 24 Feb 2015 07:04 Thomas LEBRUN <notifications@github.com> ha
scritto:

**Comment by ThomasLebrun** [comment]
Good catch, indeed....
I've made the changed :)

Date: Wed, 25 Feb 2015 05:25:00 -0800

**Pull request merged**
