### PR TITLE
Adding OSD controls

### PR DESCRIPTION
**Pull request by jg33**
Hey- just wanted to add an option to disable on-screen display at launch. Working on a mini media server.

Thanks- great work!

: j

### CODE REVIEW

**Comment by alepez** [comment]
thanks for your contribution!

**Comment by jg33** [comment]
no problem! Also, what branch of omxplayer are you using? I’m trying to get multiple files to work.

: j

**Comment by alepez** [comment]
I'm sorry, but mow I'm not using omxplayer at all. I made this module for a project some years ago and I haven't used omxplayer since then.

**Comment by jg33** [comment]
Ok- thanks!
: j

On Thu, Jan 28, 2016 at 12:29 AM, Alessandro Pezzato <notifications@github.com>
wrote:
I'm sorry, but mow I'm not using omxplayer at all. I made this module for a
project some years ago and I haven't used omxplayer since then.

—
Reply to this email directly or view it on GitHub
[https://github.com/alepez/omxdirector/pull/12#issuecomment-176050043] .[https://github.com/notifications/beacon/AB7KfJfUXRLh1MRLjuXfE89Vkknlu3liks5pecjXgaJpZM4HOEtz.gif]

**Comment by jg33** [comment]
Thanks!
: j

On Fri, Feb 12, 2016 at 4:12 AM, Alessandro Pezzato <notifications@github.com>
wrote:
Merged #12 [https://github.com/alepez/omxdirector/pull/12] .

—
Reply to this email directly or view it on GitHub
[https://github.com/alepez/omxdirector/pull/12#event-548448126] .[https://github.com/notifications/beacon/AB7KfOzQ1X3fNjgrem9nF3Q3iR4wshaIks5pjcOvgaJpZM4HOEtz.gif]

**Pull request merged**
